/* eslint-disable @typescript-eslint/no-explicit-any */
import { supabase } from "@/integrations/supabase/client";

/**
 * Loosely typed handle for the admin screens. The generated Database types
 * are regenerated by tooling and lag behind new columns (e.g. is_special),
 * and RLS is what actually protects the data, so typing here adds little.
 */
export const adminDb: any = supabase;
